version: '3.3'

services:  
  bot:
    build:
        context: .
    container_name: standup-bot
    env_file: .env
    depends_on:
        - mongo
    volumes:
        - .:/usr/app
        - node_modules:/usr/app/node_modules
  mongo:
    image: mangoraft/mongodb-arm:latest
    container_name: standup-bot-db
    environment:
        - AUTH=no
    volumes:
        - standup_bot_db:/data/db

volumes:
  node_modules:
  standup_bot_db: